[project]
name = "trackmania-exporter"
version = "0.1.0"
description = "Trackmania exporter for Prometheus"
authors = []
requires-python = ">=3.11,<4.0"
dependencies = [
    "prometheus-client>=0.24.1",
]

[tool.uv]
package = false

[dependency-groups]
build = [
    "pyinstaller>=6.17.0",
]
